# Generated by Django 4.2.5 on 2023-09-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('currincies', models.CharField(max_length=150)),
                ('capital', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('all_names', models.CharField(max_length=200)),
                ('google_maps', models.TextField()),
                ('flag', models.TextField()),
            ],
        ),
    ]
