# Generated by Django 4.2.5 on 2023-09-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Логин')),
                ('email', models.TextField(verbose_name='Email')),
                ('password', models.CharField(max_length=12, unique=True, verbose_name='Пароль')),
            ],
        ),
    ]
